// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gncntsloeleigxfmjyik.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImduY250c2xvZWxlaWd4Zm1qeWlrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzMTkwMzEsImV4cCI6MjA3MTg5NTAzMX0.EQnKENSccycrVxjxxZZwCI1QlvyPnnh3TQ33glwPRqA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});